### ISSUE TITLE
I'm afraid it doesn't actually work on nvda 2022.2/2022.3

### ISSUE THREAD

**Issue by zersiax** [blindpandas/chessmart#1]
Just tried  to install this one, but get the error below when trying to run it:

Error importing global plugin chessmart
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\__init__.py", line 43, in <module>
    from .graphical_interface.new_game_dialog import NewGameOptionsDialog
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\graphical_interface\new_game_dialog.py", line 12, in <module>
    from ..internet_chess import LichessAPIClient
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\internet_chess\__init__.py", line 11, in <module>
    from .lichess import LichessAPIClient
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\internet_chess\lichess.py", line 40, in <module>
    import lichess_client
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\lib\lichess\lichess_client\__init__.py", line 1, in <module>
    from lichess_client.clients import APIClient
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\lib\lichess\lichess_client\clients\__init__.py", line 1, in <module>
    from lichess_client.clients.client import APIClient
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\lib\lichess\lichess_client\clients\client.py", line 2, in <module>
    from lichess_client.clients.base_client import BaseClient
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\lib\lichess\lichess_client\clients\base_client.py", line 7, in <module>
    from aiohttp import ClientSession, ClientTimeout
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\lib\lichess\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\lib\lichess\aiohttp\client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "C:\Users\flori\AppData\Roaming\nvda\addons\chessmart\globalPlugins\chessmart\lib\lichess\aiohttp\http.py", line 71, in <module>
    http.server.BaseHTTPRequestHandler.responses
AttributeError: module 'http' has no attribute 'server'

Might be a capitalization thing, or it's just broken outright :)

**Comment by ivnc** [comment]
@zersiax have you any add-on from André, such as Braille Extender, Markdown Forever etc. installed? Try disabling it, that may do the trick. An user has reported the exact same error via Facebook to the NVDA.es page and he determined that was a conflict with Markdown Forever. We tried to reproduce it and discovered that it happens also with BrailleExtender. I suspect that one of these add-ons, or even this one itself, may be patching the http module and that patch affects Chessmart initialization.

**Comment by denizsincar29** [comment]
just use your own http module. why does something patch global things? it'd be nice if an addon can patch something just in their namespace!
